### ISSUE TITLE
TypeError when importing ssh keys from github

### ISSUE THREAD

**Issue by lyneca** [hashbang/hashbangctl#16]
Importing my pubkey from github and then saving changes results in a TypeError:

``` python
Traceback (most recent call last):
  File "/usr/local/bin/hashbangctl", line 186, in <module>
  File "/usr/local/bin/hashbangctl", line 86, in ldap_sync
  File "/usr/local/lib/python2.7/dist-packages/provisor/provisor.py", line 271, in modify_user
  File "/usr/local/lib/python2.7/dist-packages/ldap/ldapobject.py", line 401, in modify_s
  File "/usr/local/lib/python2.7/dist-packages/ldap/ldapobject.py", line 398, in modify
  File "/usr/local/lib/python2.7/dist-packages/ldap/ldapobject.py", line 370, in modify_ext
  File "/usr/local/lib/python2.7/dist-packages/ldap/ldapobject.py", line 106, in _ldap_call
TypeError: ('expected a string in the list', u'[MY PUBLIC KEY]')
```

**Comment by lyneca** [comment]
[This article](http://stackoverflow.com/questions/13830574/ldap-in-django-required-to-pass-unicode-password-as-string) says that it's a problem with the Python LDAP module and to call `str()` on unicode strings as a quick fix.
